# Generated by Django 5.2.13 on 2026-04-26 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_type', models.CharField(choices=[('mechanical', 'Mechanical Shop'), ('petrol_pump', 'Petrol Pump')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phone', models.CharField(max_length=32)),
                ('document_url', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='pending', max_length=32)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=32)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_liters', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='shops.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shops.shopprofile')),
                ('vehicle_types', models.ManyToManyField(blank=True, related_name='services', to='shops.vehicletype')),
            ],
        ),
        migrations.AddIndex(
            model_name='shopprofile',
            index=models.Index(fields=['shop_type', 'status'], name='shops_shopp_shop_ty_34665c_idx'),
        ),
        migrations.AddIndex(
            model_name='shopprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='shops_shopp_latitud_7c0dc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fuelinventory',
            unique_together={('shop', 'fuel_type')},
        ),
    ]
