# Generated by Django 5.2.13 on 2026-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
